### ISSUE TITLE
Copyright info in Windows Installer Package comments

### ISSUE THREAD

**Issue by keremispirli** [TorXakis/SourceWindowsInstaller#16]
![image](https://user-images.githubusercontent.com/661967/31499327-c421c48a-af64-11e7-923d-d16ebf3f9d1a.png)

Full text says: _Copyright (c) 2015-2017 TNO and Radboud University_

After #15, this is the only TNO remark left that I could find in Windows Installer Package project. Should this comment be changed, too?

**Comment by pjljvandelaar** [comment]
Let's ask Harm or Frans

**Comment by keremispirli** [comment]
@HarmMunkESI

**Comment by ghost** [comment]
What about (c) TorXakis foundation/Consortium/...?

**Comment by keremispirli** [comment]
Do we use TorXakis Foundation or TorXakis Consortium anywhere else?
Maybe we can say _torxakis.org_ again?

_Copyright (c) 2015-2017 torxakis.org_

**Comment by keremispirli** [comment]
_torxakis.org_ approved by Harm
