### ISSUE TITLE
Make config file optional

### ISSUE THREAD

**Issue by keremispirli** [TorXakis/SourceWindowsInstaller#22]
TorXakis can run without a configuration (_.torxakis.yaml_) file, so even if we can't install this file the installer should not fail.

Actually it is already possible to exclude "Configuration" feature by choosing Custom Setup. So the setup should not be interrupted because of unavailability of user home directory.

**Comment by keremispirli** [comment]
I couldn't find anything about this, so I asked in SO:
https://stackoverflow.com/questions/47413121/how-to-ignore-invalid-drive-for-an-optional-file-component

**Comment by pjljvandelaar** [comment]
Alternative: in error message describe 'you need a "custom" install in which the feature "config" will not be installed.
Of course, use the exact words as used by Wix installer (i don't know them by heart)

**Comment by keremispirli** [comment]
MSI installer halts the installation if the drive is not available, so it's not possible to Custom install either.

**Comment by pjljvandelaar** [comment]
You can of course ask the users to restart installation.

**Comment by pjljvandelaar** [comment]
E.g. add a note: installation failed since optional file Can't be copied to users home directory. You can install torxakis using custom install to exclude this file.

**Comment by keremispirli** [comment]
They can't use Custom Install to exclude that file; they are never presented with that option. As soon as the installer is launced, error message is shown and installer prematurely ends.
