### ISSUE TITLE
TorXakis can be installed without TorXakis

### ISSUE THREAD

**Issue by keremispirli** [TorXakis/SourceWindowsInstaller#23]
It is possible to exclude TorXakis feature during TorXakis installation, by choosing Custom Setup.

![image](https://user-images.githubusercontent.com/661967/33018987-dc297804-cdf8-11e7-8416-82542937c962.png)

It doesn't make sense; TorXakis and Z3 features should be obligatory for installation.

**Comment by pjljvandelaar** [comment]
Z3 should not be necessary.
It can already be installed by the user.
Cvc4 can also be used.
