### ISSUE TITLE
SMT Solvers are provided manually

### ISSUE THREAD

**Issue by keremispirli** [TorXakis/SourceWindowsInstaller#3]
Currently SMT Solver locations are passed as parameters while building the installer. They should be fetched programmatically from a trusted source.

**Comment by pjljvandelaar** [comment]
When?
* When user installs TorXakis, Z3 and CVC4 are also downloaded?
* During building TorXakis installer, also Z3 and cvc4 are downloaded... yet which version? -> still needs input from builder of TorXakis installer.

**Comment by keremispirli** [comment]
While building the installer.
Z3 and CVC4 were and still are parameters to the batch file that creates the installer. Right now I have "z3-4.5.0-x64-win" and "cvc4-2017-06-13-win32-opt" versions on my machine, so when I build an installer it includes these versions; both of which are wrong:
- TorXakis is installed under "Program Files (x86)", so z3 should also be x86.
- TorXakis expects "cvc4-2017-04-27-win32-opt"

Ideally, versions of these solvers and the sources to fetch them from should be predetermined.

**Comment by pjljvandelaar** [comment]
TorXakis can work with z3-x64, so x86 is not needed.
Yet, one would like to install z3 in the approriate directory (now it is a part of TorXakis)
